#!/usr/bin/python

import sys
import os
from subprocess import call

import exile

def resolveReference(file):
    if exile.isReference(file):
        with open(file, 'r') as data:
            location = data.readlines()[1].strip().split('/')
        repo = location[0]
        hash = location[1]
        local = exile.rootDir() + os.sep + repo + os.sep + hash
        if not os.path.exists(local):
            print 'Pulling %s from %s' % (hash, repo)
            exile.get(repo, hash)

        print 'Refreshing ' + file
        os.remove(file)
        call(['git', 'checkout', file])

exile.forEachSubtree(sys.argv[1:], resolveReference)
